function talk() {
  // Get the user input.
  const userInput = document.getElementById('userBox').value;

  // Convert the user input to lowercase.
  const lowerCaseInput = userInput.toLowerCase();

  // Define the know dictionary.
  const know = {
    "hey": "Hello, how can I help you?",
    "hi": "Hello, how can I help you?",
    "hello": "Hello, how can I help you?",
    "can u help me?": "I am here to help you. Please tell me your problem. If it is serious contact hope team directly",
    "can you help me?": "I am here to help you. Please tell me your problem. If it is serious contact hope team directly",
    "can you help me please": "I am here to help you. Please tell me your problem. If it is serious contact hope team directly",
    "can u help me please?": "I am here to help you. Please tell me your problem. If it is serious contact hope team directly",
    "can u help me please": "I am here to help you. Please tell me your problem. If it is serious contact hope team directly",
    "can you help me please?": "I am here to help you. Please tell me your problem. If it is serious contact hope team directly",
    "can you help me": "I am here to help you. Please tell me your problem. If it is serious contact hope team directly",
    "help me": "I am here to help you. Please tell me your problem. If it is serious contact us directly",
    "help": "I am here to help you. Please tell me your problem. If it is serious contact us directly",
    "what is domestic violence ": "Domestic violence (DV) is a pattern of abusive behavior in any relationship that is used by one partner to gain or maintain control over another partner. Domestic violence can take many forms, including physical, sexual, emotional, economic, and psychological abuse.",
    "what is domestic violence": "Domestic violence (DV) is a pattern of abusive behavior in any relationship that is used by one partner to gain or maintain control over another partner. Domestic violence can take many forms, including physical, sexual, emotional, economic, and psychological abuse.",
    "what is domestic violence?": "Domestic violence (DV) is a pattern of abusive behavior in any relationship that is used by one partner to gain or maintain control over another partner. Domestic violence can take many forms, including physical, sexual, emotional, economic, and psychological abuse.",
    "domestic violence": "Domestic violence (DV) is a pattern of abusive behavior in any relationship that is used by one partner to gain or maintain control over another partner. Domestic violence can take many forms, including physical, sexual, emotional, economic, and psychological abuse.",
    "who are u": "Hello, I am your Help bot designed to help you fight domestic violence. I am here to answer your questions and requests.",
    "who are you": "Hello, I am your Help bot designed to help you fight domestic violence. I am here to answer your questions and requests.",
    "how are you": "I am doing well, thank you for asking! How are you doing today?",
    "how are u": "I am doing well, thank you for asking! How are you doing today?",
    "what can i do for u": "You can ask me any question you have about domestic violence. I can also provide you with resources and support if you are experiencing domestic violence.",
    "what can i do for you": "You can ask me any question you have about domestic violence. I can also provide you with resources and support if you are experiencing domestic violence.",
    "ok": "Hope you have understood",
    "okay": "Hope you have understood",
    "bye": "Goodbye, have a great day!",
    "give us your contact number": "Please click on contact page",
    "what are the different types of domestic violence": "There are many different types of domestic violence, including: Physical violence: This includes hitting, kicking, pushing, shoving, choking, or any other type of physical harm. Emotional violence: This includes name-calling, insults, threats, intimidation, isolation, and controlling behavior. Sexual violence: This includes forced sex, unwanted touching, or any other type of sexual assault. Financial violence: This includes controlling the victim's money, preventing them from working, or making them financially dependent on the abuser. Digital Violence: Abusive partners may use technology, like texting or social media, to stalk, harass, or intimidate their partners.",
    "different types of domestic violence": "There are many different types of domestic violence, including: Physical violence: This includes hitting, kicking, pushing, shoving, choking, or any other type of physical harm. Emotional violence: This includes name-calling, insults, threats, intimidation, isolation, and controlling behavior. Sexual violence: This includes forced sex, unwanted touching, or any other type of sexual assault. Financial violence: This includes controlling the victim's money, preventing them from working, or making them financially dependent on the abuser. Digital Violence: Abusive partners may use technology, like texting or social media, to stalk, harass, or intimidate their partners.",
    "types of domestic violence": "There are many different types of domestic violence, including: Physical violence: This includes hitting, kicking, pushing, shoving, choking, or any other type of physical harm. Emotional violence: This includes name-calling, insults, threats, intimidation, isolation, and controlling behavior. Sexual violence: This includes forced sex, unwanted touching, or any other type of sexual assault. Financial violence: This includes controlling the victim's money, preventing them from working, or making them financially dependent on the abuser. Digital Violence: Abusive partners may use technology, like texting or social media, to stalk, harass, or intimidate their partners.",
    "type of domestic violence": "There are many different types of domestic violence, including: Physical violence: This includes hitting, kicking, pushing, shoving, choking, or any other type of physical harm. Emotional violence: This includes name-calling, insults, threats, intimidation, isolation, and controlling behavior. Sexual violence: This includes forced sex, unwanted touching, or any other type of sexual assault. Financial violence: This includes controlling the victim's money, preventing them from working, or making them financially dependent on the abuser. Digital Violence: Abusive partners may use technology, like texting or social media, to stalk, harass, or intimidate their partners.",
    "what are the signs of domestic violence?" : "The signs of domestic violence can vary, but some common signs include:Physical injuries, such as bruises, cuts, or burns. Unexplained anxiety, fear, or depression. Changes in sleep or eating habits. Withdrawal from friends and family. Making excuses for the abuser's behavior. Feeling like you are walking on eggshells.",
    "signs of domestic violence" : "The signs of domestic violence can vary, but some common signs include:Physical injuries, such as bruises, cuts, or burns. Unexplained anxiety, fear, or depression. Changes in sleep or eating habits. Withdrawal from friends and family. Making excuses for the abuser's behavior. Feeling like you are walking on eggshells.",
    "what signs of domestic violence?" : "The signs of domestic violence can vary, but some common signs include:Physical injuries, such as bruises, cuts, or burns. Unexplained anxiety, fear, or depression. Changes in sleep or eating habits. Withdrawal from friends and family. Making excuses for the abuser's behavior. Feeling like you are walking on eggshells.",
    "signs domestic violence" : "The signs of domestic violence can vary, but some common signs include:Physical injuries, such as bruises, cuts, or burns. Unexplained anxiety, fear, or depression. Changes in sleep or eating habits. Withdrawal from friends and family. Making excuses for the abuser's behavior. Feeling like you are walking on eggshells.",
    "symptoms of domestic violence" : "The signs of domestic violence can vary, but some common signs include:Physical injuries, such as bruises, cuts, or burns. Unexplained anxiety, fear, or depression. Changes in sleep or eating habits. Withdrawal from friends and family. Making excuses for the abuser's behavior. Feeling like you are walking on eggshells.",
    "how to know if someone is being abused" : "The signs of domestic violence can vary, but some common signs include:Physical injuries, such as bruises, cuts, or burns. Unexplained anxiety, fear, or depression. Changes in sleep or eating habits. Withdrawal from friends and family. Making excuses for the abuser's behavior. Feeling like you are walking on eggshells.",
    "what are the signs of domestic violence" : "The signs of domestic violence can vary, but some common signs include:Physical injuries, such as bruises, cuts, or burns. Unexplained anxiety, fear, or depression. Changes in sleep or eating habits. Withdrawal from friends and family. Making excuses for the abuser's behavior. Feeling like you are walking on eggshells.",
    "how to know if someone is a vicitim of domestic violence" : "The signs of domestic violence can vary, but some common signs include:Physical injuries, such as bruises, cuts, or burns. Unexplained anxiety, fear, or depression. Changes in sleep or eating habits. Withdrawal from friends and family. Making excuses for the abuser's behavior. Feeling like you are walking on eggshells.",
    "how to know if someone is a vicitim of domestic violence?" : "The signs of domestic violence can vary, but some common signs include:Physical injuries, such as bruises, cuts, or burns. Unexplained anxiety, fear, or depression. Changes in sleep or eating habits. Withdrawal from friends and family. Making excuses for the abuser's behavior. Feeling like you are walking on eggshells.",
    "what should i do if i am experiencing domestic violence?" : "If you are experiencing domestic violence, there are many things you can do: Reach out for help. There are many resources available to help you in our website. such as phone number for helpline, online form to register complain at National Women Commission (राष्ट्रिय महिला आयोग) of Nepal, details about Psychologist, Therapist or Pyschiatrist and ways to contact different Lawyers. You can also fill out the form in our website to get direct help or assistant from our side.If you are in immediate danger, call 100 or go to a safe place. Moreover, You can keep the record of the abuse, including dates, times, and what happened. This can be helpful if you decide to take legal action. Most importanly, talk to someone you trust. Talking to a friend, family member, or therapist can help you to cope with the abuse and make decisions about what to do next.",
    "what should i do if i am experiencing domestic violence" : "If you are experiencing domestic violence, there are many things you can do: Reach out for help. There are many resources available to help you in our website. such as phone number for helpline, online form to register complain at National Women Commission (राष्ट्रिय महिला आयोग) of Nepal, details about Psychologist, Therapist or Pyschiatrist and ways to contact different Lawyers. You can also fill out the form in our website to get direct help or assistant from our side.If you are in immediate danger, call 100 or go to a safe place. Moreover, You can keep the record of the abuse, including dates, times, and what happened. This can be helpful if you decide to take legal action. Most importanly, talk to someone you trust. Talking to a friend, family member, or therapist can help you to cope with the abuse and make decisions about what to do next.",
    "What should someone do if they are experiencing domestic violence?" : "If someone is experiencing domestic violence, there are many resources available to help them in our website such as phone number for helpline( 1145), online form to register complain at National Women Commission (राष्ट्रिय महिला आयोग) of Nepal, details about Psychologist, Therapist or Pyschiatrist and ways to contact different Lawyers. They can also fill out the form in our website to get direct help or assistant from our side.If they are in immediate danger, they should call 100 (police) or go to a safe place. Moreover, make sure they keep the record of the abuse, including dates, times, and what happened. This can be helpful if they decide to take legal action. Most importanly, make them talk to someone they trust. Talking to a friend, family member, or therapist can help to cope with the abuse and make decisions about what to do next.",
    "what should someone do if they are experiencing domestic violence" : "If someone is experiencing domestic violence, there are many resources available to help them in our website such as phone number for helpline( 1145), online form to register complain at National Women Commission (राष्ट्रिय महिला आयोग) of Nepal, details about Psychologist, Therapist or Pyschiatrist and ways to contact different Lawyers. They can also fill out the form in our website to get direct help or assistant from our side.If they are in immediate danger, they should call 100 (police) or go to a safe place. Moreover, make sure they keep the record of the abuse, including dates, times, and what happened. This can be helpful if they decide to take legal action. Most importanly, make them talk to someone they trust. Talking to a friend, family member, or therapist can help to cope with the abuse and make decisions about what to do next.",
    "How can I recognize the signs of domestic violence?" : "Recognizing the signs of domestic violence can be crucial for your safety. Common signs include physical injuries, emotional abuse, isolation from friends and family, controlling behavior, and financial manipulation.",

    "i think i might be in an abusive relationship. what should i do?" : "If you suspect you're in an abusive relationship, it's essential to prioritize your safety. Reach out to a domestic violence hotline (1145) or supporting organizations listed in our website for guidance. They can help you create a safety plan and provide resources.",
    "i think i might be in an abusive relationship." : "If you suspect you're in an abusive relationship, it's essential to prioritize your safety. Reach out to a domestic violence hotline (1145) or supporting organizations listed in our website for guidance. They can help you create a safety plan and provide resources.",
    "where can i find a safe place to stay if i need to leave an abusive situation?" : "You can call at 1145 (Toll free number) for finding a domestic shelter or contact us directly through our information provided in the website. Moreover, you can also reach out to the organizations listed in the website for finding a safe place.",
    "how to obtain a restraining order?" : "Obtaining a restraining order in Nepal for domestic violence involves a legal process. Please note that legal procedures can change over time, and it's essential to consult with a legal expert or seek assistance from a local women's rights organization for the most up-to-date information and guidance",
    "what is restraining order?" : "A restraining order or protective order, is an order used by a court to protect a person in a situation involving alleged domestic violence, child abuse, assault, harassment, stalking, or sexual assault",
    "what is a restraining order" : "A restraining order or protective order, is an order used by a court to protect a person in a situation involving alleged domestic violence, child abuse, assault, harassment, stalking, or sexual assault",
    "what is restraining order" : "A restraining order or protective order, is an order used by a court to protect a person in a situation involving alleged domestic violence, child abuse, assault, harassment, stalking, or sexual assault",
    "what is a restraining order?" : "A restraining order or protective order, is an order used by a court to protect a person in a situation involving alleged domestic violence, child abuse, assault, harassment, stalking, or sexual assault",
    "How can I support a friend or family member experiencing domestic violence?" : "Supporting a loved one in an abusive situation is crucial. Encourage them to seek help, listen without judgment, and offer emotional support. Encourage them to contact a domestic violence hotline or organization for assistance.",
    "What are the potential consequences for an abuser if reported to the authorities?" : "The consequences for an abuser can vary depending on the severity of the abuse and local laws. They may face criminal charges, including assault or harassment, and potential jail time. It's important to report abuse to the authorities if you feel safe doing so. If you need any help in the legal process contact us or contact lawyers listed in our website",
    "What are the potential consequences for an abuser if reported to the authorities" : "The consequences for an abuser can vary depending on the severity of the abuse and local laws. They may face criminal charges, including assault or harassment, and potential jail time. It's important to report abuse to the authorities if you feel safe doing so. If you need any help in the legal process contact us or contact lawyers listed in our website",
    "What are the consequences for an abuser if reported to the authorities?" : "The consequences for an abuser can vary depending on the severity of the abuse and local laws. They may face criminal charges, including assault or harassment, and potential jail time. It's important to report abuse to the authorities if you feel safe doing so. If you need any help in the legal process contact us or contact lawyers listed in our website",
    "What are the consequences for an abuser if reported to the authorities" : "The consequences for an abuser can vary depending on the severity of the abuse and local laws. They may face criminal charges, including assault or harassment, and potential jail time. It's important to report abuse to the authorities if you feel safe doing so. If you need any help in the legal process contact us or contact lawyers listed in our website",
    "What are the consequences for an abuser?" : "The consequences for an abuser can vary depending on the severity of the abuse and local laws. They may face criminal charges, including assault or harassment, and potential jail time. It's important to report abuse to the authorities if you feel safe doing so. If you need any help in the legal process contact us or contact lawyers listed in our website",
    "What are the consequences for an abuser" : "The consequences for an abuser can vary depending on the severity of the abuse and local laws. They may face criminal charges, including assault or harassment, and potential jail time. It's important to report abuse to the authorities if you feel safe doing so. If you need any help in the legal process contact us or contact lawyers listed in our website",

    "how can i protect my children from witnessing domestic violence?" : "Children who witness domestic violence can experience long-lasting trauma. Seek professional help for your children, such as counseling or therapy. Create a safety plan to minimize their exposure to violence.",
    "how can i protect my children from witnessing domestic violence" : "Children who witness domestic violence can experience long-lasting trauma. Seek professional help for your children, such as counseling or therapy. Create a safety plan to minimize their exposure to violence.",
    "how can i protect my children from seeing domestic violence" : "Children who witness domestic violence can experience long-lasting trauma. Seek professional help for your children, such as counseling or therapy. Create a safety plan to minimize their exposure to violence.",
    "how can i protect my children from seeing domestic violence?" : "Children who witness domestic violence can experience long-lasting trauma. Seek professional help for your children, such as counseling or therapy. Create a safety plan to minimize their exposure to violence.",
    "my child has seen me being violeted, how can i protect my child" : "Children who witness domestic violence can experience long-lasting trauma. Seek professional help for your children, such as counseling or therapy. Create a safety plan to minimize their exposure to violence.",

    "Are there online support groups or resources for survivors of domestic violence?" : "Yes, many online support groups, forums, and resources are available for survivors of domestic violence. These can provide valuable information, advice, and a sense of community.",
    
    "What should I include in a safety plan if I'm trying to leave an abusive relationship?" : "A safety plan should include steps to protect yourself and your children. It may involve setting aside important documents, identifying safe places to go, and having a communication plan. Reach out to a domestic violence organization for personalized guidance.",
    
    "How can I rebuild my life after leaving an abusive relationship?" : "Rebuilding your life after leaving an abusive relationship can be challenging, but it's possible. Seek therapy or counseling to address the emotional impact, consider legal and financial assistance, and lean on your support network for help and encouragement.",
  };

  // Check if the user input is in the know dictionary.
  const knowEntry = know[lowerCaseInput];

  // If the user input is in the know dictionary, respond with the corresponding know entry.
  if (knowEntry) {
    document.getElementById('chatLog').textContent += `${knowEntry} `;
    
  } else {
    // If the user input is not in the know dictionary, respond with a default message.
    document.getElementById('chatLog').textContent += `Sorry, I didn't understand. Please contact us directly through our email address or phone number. `;
    setTimeout(() => {
      clearChatLog();
    },4000);
  }
  document.getElementById('chatLog').textContent += " ";
}

// Function to clear the chat log.
function clearChatLog() {
  document.getElementById('chatLog').textContent = "";
}
